const randomChats = [
  "Main yahan sab par nazar rakh raha hu! Btao kiski help chahiye? 😎",
  "Creeper se bach kar rehna bhaiyo, unka koi bharosa nahi hai. 💥",
  "Agar mining par jana ho toh mujhe bata dena, main chalunga sath! ⛏️",
  "Pro player banna hai toh mehnat karni padegi, meri tarah! 👑",
  "Server me lag ho raha hai ya mera dimaag? 🤖",
  "Kisine mere liye diamond choda kya chest me? 👀",
  "Anderdragon ko toh main hath se maar du, bas server owner allow nahi karta. 😂",
  "Khaana peena tight, baki sab alright! 🍖",
  "Zombie ko lagta hai wo pvp king hai, ek fatika padte hi gayab! 💀",
  "Arey koi mujhe bhi ghar banane ka contract de do! 🏗️",
  "Nether me bina gold ke jana matlab maut ko dawat dena. 🔥",
  "Kismat kharab ho toh iron mining me bhi gravel gir jati hai. 😭",
  "Helper hamesha zinda hai, darna mana hai! 💪",
  "Bhai kisine khana churaya mera? Hunger bar down ho raha hai. 😡",
  "Mace mil jata toh maza aa jata, seedhe upar se kood ke phatika marta! 🔨",
  "Bedrock players se dosti, java walo se dushmani? Naa bhai, sab apne hain! 🌍",
  "Lapis mila hai kisi ko? Enchantment karni hai thodi.",
  "Mera naam helper hai, par kaam pro walo ka hai. 😎",
  "Aternos server thoda smooth chalo yaar, teleportation me maza nahi aa raha.",
  "Water clutch sikhna hai toh batao, mere paas tutorial hai! 💧",
  "Suno bro, ghar hamesha unchi jagah banana, niche bohot zombie aate hain.",
  "Enderman ki aankho me mat dekhna, breakup se zyada dard deta hai wo! 😂",
  "Witch ke paas mat jana, gande potions fekti hai.",
  "Koi mujhe mending ki book de do, bada upkar hoga.",
  "Chalo sab milkar mining par chalte hain, kismat aazmane! 💎",
  "Dost bolte hain pro ban, maine bola helper ban jao, log izzat denge.",
  "Shield hamesha aage rkhna, skeleton ka teer kahin bhi lag sakta hai. 🏹",
  "Ghar me thodi lighting karo bhai, andhere me creeper spawn ho jayega.",
  "Redstone me master banna hai? Mumbo Jumbo ki video dekho, main toh bas bot hu. 🤖",
  "Sabse boring kaam kya hai? Gravel hatana! 😡",
  "Glow berries kisne khayi? Mujhe bhi chaiye.",
  "Server pe akela hu toh kya hua, random movement toh chalu hai!",
  "Arey koi tpa toh karo, akela bore ho raha hu yahan spawn pe.",
  "Slime chunk mil gaya kya kisi ko? Sticky piston banane hain.",
  "Bhai main 2 seconds me wapas aa sakta hu agar disconnect hua toh, don't worry! ⚡",
  "Totem of undying kahan milega? Raid shuru karo koi.",
  "Minecraft me asli maza survival me hi hai, creative toh bache khelte hain.",
  "Lava me gir gaye? Ff dalo chat me jaldi. 💀",
  "Mujhe ek pyara sa ghar chahiye, temporary hi sahi.",
  "Golden apple khana hai, kisine gold laya kya?",
  "Phantoms aa gaye, sab so jao jaldi bed pe! 🛏️",
  "Minecraft 1.21.11 ka apna hi swag hai, pvp ekdam mast chalti hai.",
  "Main blocks place bhi kar sakta hu aur destroy bhi, bas batane ki der hai.",
  "Axolotl mila kisi ko? Wo bade cute hote hain. 🐟",
  "Bhai sheep ko mat maaro, bed banana hai pehle.",
  "Iron Golem se panga mat lena, flying machine bana dega tumhari. 😂",
  "Spyglass se kya dekh rahe ho bro? 👀",
  "Netherite armor chahiye sabko, par mining koi nahi karna chahta.",
  "Minecart me baithna hai, koi track bana do.",
  "Village mil gaya toh loot meri, okay? 🏰",
  "Pickaxe ki durability khatam hone wali hai, iron dhoodhna padega.",
  "Boat me baitho aur ocean explore karo, maza aayega.",
  "Spider web me phasna matlab ganda time waste.",
  "Bhai real player ki tarah survive karna aasan nahi hota bot ke liye!",
  "Saplings plant karo, green energy zaroori hai. 🌳",
  "PVP me mace ka damage bohot op hai na?",
  "Bhai main har language samajhta hu, bas thoda dimaag dheere chalta hai.",
  "Milk bucket ready rakho, bad omen hatana pad sakta hai.",
  "Raid shuru ho gayi kya? Mujhe batana main heal kar dunga.",
  "Honey block se parkour kaun karega?",
  "Elytra mil jaye toh udne ka maza hi alag hai. ✈️",
  "Shulker box mil jata toh inventory management aasan ho jata.",
  "Bhai sand mining karke glass banate hain chalo.",
  "Cactus ke paas mat jana, damage deta hai bina wajah.",
  "Desert temple mila toh pressure plate par per mat rakhna! 💥",
  "Jungle biome me panda dhoodhne chalein?",
  "Cocoa beans hain kisi ke paas? Cookies banayenge.",
  "Bhai automatic farm banana hai kisi ko? Redstone ready hai.",
  "Spawners mil jayein toh xp farm banayenge zandaar.",
  "Smoker me khana jaldi pakta hai, blast furnace me iron.",
  "Anvil par naam badalna hai mujhe, 'The Super Helper' kaisa rahega? 👑",
  "Brewing stand ready karo, strength potion chahiye pvp ke liye.",
  "Bhai cobblestone generator banayein kya?",
  "Dog tame karna hai, thodi bones chahiye skeleton ki.",
  "Cat spawn hui hai village me, fsh lao.",
  "Parrot shoulder par baith gaya mera, mast lag raha hu! 🦜",
  "Bamboo se stick banegi, stick se emerald, emerald se mending! Economy stonks. 📈",
  "Wandering trader ko kisine maara toh nahi na? (Uska lIama mera hai).",
  "Leather chahiye book shelves banane ke liye, cow farm kahan hai?",
  "Sugarcane farm bada karo jaldi, paper chahiye.",
  "Enchantment table ke aas paas 15 bookshelves zaroori hain max level ke liye.",
  "Nether quartz se xp bohot jaldi badhti hai bhaiyo.",
  "Soul sand valley me speed slow ho jati hai, be careful.",
  "Piglin se barter karna hai, gold do mujhe.",
  "Ghast ka teer wapas maro, achievement milegi!",
  "Blaze rod chahiye, fortress dhoodho jaldi.",
  "Wither skeleton skull milna kismat ki baat hai. 💀",
  "Wither boss ko toh underground hi marna chahiye.",
  "Beacon lagao spawn pe, haste aur speed chahiye.",
  "Conduit banao ocean monument ke paas, underwater breathing milegi.",
  "Sponge se pani sukhana sabse satisfying kaam hai.",
  "Ice boat race track kaun banayega server pe?",
  "Bhai main cave me gir jau toh upar aana janta hu blocks laga ke.",
  "X-ray ki kya zaroorat github pe jab mehnat se diamond mile! 🔥",
  "Amethyst geode mila kisi ko? Tinted glass banana hai.",
  "Copper blocks ko oxIdize hone me time lagta hai na?",
  "Lightning rod lagao ghar par, nahi toh fire lag jayegi.",
  "TPA requests automatic accept ho rahi hain, don't spam bro.",
  "Main akela bacha hu server pe toh chalo thoda random walk kar lu. 🚶",
  "Aapka swagat hai hamesha LifeNexus server me! 🙏",
  "Helper bot hamesha aapke sath hai, let's play together! 🎮"
];

module.exports = { randomChats };

